package com.co.challenge.devsubankaccount.repositories.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.sql.Timestamp;
import java.util.UUID;

/**
 * Movement generated by hbm2java
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "movement", catalog = "challenge_devsu_account")
public class Movement implements java.io.Serializable {

    @Id
    @GeneratedValue(generator = "UUID")
    @GenericGenerator(name = "UUID", strategy = "org.hibernate.id.UUIDGenerator")
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(name = "id", length = 36, columnDefinition = "varchar(36)", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JdbcTypeCode(SqlTypes.CHAR)
    @JoinColumn(name = "account_id", nullable = false)
    private Account account;

    @Column(name = "movement_type", nullable = false, length = 16)
    private String movementType;

    @Column(name = "amount", precision = 22, scale = 0)
    private Double amount;

    @Column(name = "balance", precision = 22, scale = 0)
    private Double balance;

    @CreationTimestamp
    @Column(name = "created_date", length = 19, updatable = false)
    private Timestamp createdDate;
}
